version: '3.9'
services:
  #Postgres Service
  db:
    container_name: drizzle-json-columns
    image: postgres:16.0
    environment:
      - POSTGRES_USER=drizzle
      - POSTGRES_PASSWORD=drizzle
      - POSTGRES_DB=drizzle_cols
      - POSTGRES_HOST=localhost
      - PGDATA=${PGDATA:-/var/lib/postgresql/data/pgdata}
    ports:
      - ${POSTGRES_PORT:-5533}:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - drizzle-network

#Docker Networks
networks:
  drizzle-network:
    name: drizzle-network
    driver: bridge

# Volumes
volumes:
  db:
    driver: local
